# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import flood_tool
import pandas as pd

class Ui_MainWindow(object):

    def __init__(self):
        self.df = pd.DataFrame()
        self._translate = QtCore.QCoreApplication.translate

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 666)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setMouseTracking(False)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_E_in = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_E_in.setObjectName("lineEdit_E_in")
        self.horizontalLayout.addWidget(self.lineEdit_E_in)
        self.label_n1 = QtWidgets.QLabel(self.centralwidget)
        self.label_n1.setObjectName("label_n1")
        self.horizontalLayout.addWidget(self.label_n1)
        self.lineEdit_N_in = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_N_in.setObjectName("lineEdit_N_in")
        self.horizontalLayout.addWidget(self.lineEdit_N_in)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.covB1 = QtWidgets.QPushButton(self.centralwidget)
        self.covB1.setObjectName("covB1")
        self.verticalLayout_2.addWidget(self.covB1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_lat1 = QtWidgets.QLabel(self.centralwidget)
        self.label_lat1.setObjectName("label_lat1")
        self.horizontalLayout_2.addWidget(self.label_lat1)
        self.lineEdit_Lat_out = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Lat_out.setReadOnly(True)
        self.lineEdit_Lat_out.setObjectName("lineEdit_Lat_out")
        self.horizontalLayout_2.addWidget(self.lineEdit_Lat_out)
        self.label_lon1 = QtWidgets.QLabel(self.centralwidget)
        self.label_lon1.setObjectName("label_lon1")
        self.horizontalLayout_2.addWidget(self.label_lon1)
        self.lineEdit_Lon_out = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Lon_out.setReadOnly(True)
        self.lineEdit_Lon_out.setObjectName("lineEdit_Lon_out")
        self.horizontalLayout_2.addWidget(self.lineEdit_Lon_out)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_lat2 = QtWidgets.QLabel(self.centralwidget)
        self.label_lat2.setObjectName("label_lat2")
        self.horizontalLayout_3.addWidget(self.label_lat2)
        self.lineEdit_Lat_in = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Lat_in.setObjectName("lineEdit_Lat_in")
        self.horizontalLayout_3.addWidget(self.lineEdit_Lat_in)
        self.label_lon2 = QtWidgets.QLabel(self.centralwidget)
        self.label_lon2.setObjectName("label_lon2")
        self.horizontalLayout_3.addWidget(self.label_lon2)
        self.lineEdit_Lon_in = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Lon_in.setObjectName("lineEdit_Lon_in")
        self.horizontalLayout_3.addWidget(self.lineEdit_Lon_in)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.covB2 = QtWidgets.QPushButton(self.centralwidget)
        self.covB2.setObjectName("covB2")
        self.verticalLayout_3.addWidget(self.covB2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_e2 = QtWidgets.QLabel(self.centralwidget)
        self.label_e2.setObjectName("label_e2")
        self.horizontalLayout_4.addWidget(self.label_e2)
        self.lineEdit_E_out = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_E_out.setReadOnly(True)
        self.lineEdit_E_out.setObjectName("lineEdit_E_out")
        self.horizontalLayout_4.addWidget(self.lineEdit_E_out)
        self.label_n2 = QtWidgets.QLabel(self.centralwidget)
        self.label_n2.setObjectName("label_n2")
        self.horizontalLayout_4.addWidget(self.label_n2)
        self.lineEdit_N_out = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_N_out.setReadOnly(True)
        self.lineEdit_N_out.setObjectName("lineEdit_N_out")
        self.horizontalLayout_4.addWidget(self.lineEdit_N_out)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_csv = QtWidgets.QLabel(self.centralwidget)
        self.label_csv.setObjectName("label_csv")
        self.horizontalLayout_5.addWidget(self.label_csv)
        self.lineEdit_csv = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_csv.setObjectName("lineEdit_csv")
        self.horizontalLayout_5.addWidget(self.lineEdit_csv)
        self.covB3 = QtWidgets.QPushButton(self.centralwidget)
        self.covB3.setObjectName("covB3")
        self.horizontalLayout_5.addWidget(self.covB3)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.model = QtGui.QStandardItemModel()
        self.model.setHorizontalHeaderLabels(list(self.df))
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableView.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.ResizeToContents)
        self.tableView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView.setObjectName('tableView')
        self.tableView.setModel(self.model)
        
        self.verticalLayout.addWidget(self.tableView)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.covB1.clicked.connect(self.click_covB1)
        self.covB2.clicked.connect(self.click_covB2)
        self.covB3.clicked.connect(self.click_covB3)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(self._translate("MainWindow", "Coordinate Converting"))
        self.label.setText(self._translate("MainWindow", "Easting:"))
        self.label_n1.setText(self._translate("MainWindow", "Northing:"))
        self.covB1.setText(self._translate("MainWindow", "convert EN->LL"))
        self.label_lat1.setText(self._translate("MainWindow", "Latitude:"))
        self.label_lon1.setText(self._translate("MainWindow", "Longitude:"))
        self.label_lat2.setText(self._translate("MainWindow", "Latitude:"))
        self.label_lon2.setText(self._translate("MainWindow", "Longitude:"))
        self.covB2.setText(self._translate("MainWindow", "convert LL->EN"))
        self.label_e2.setText(self._translate("MainWindow", "Easting:"))
        self.label_n2.setText(self._translate("MainWindow", "Northing:"))
        self.label_csv.setText(self._translate("MainWindow", "Input your csv file:"))
        self.covB3.setText(self._translate("MainWindow", "convert"))

    def click_covB1(self):
        v1 = self.lineEdit_E_in.text()
        v2 = self.lineEdit_N_in.text()

        try:
            r1, r2 = flood_tool.get_gps_lat_long_from_easting_northing(float(v1),float(v2))
            self.lineEdit_Lat_out.setText(self._translate("MainWindow", str(r1[0])))
            self.lineEdit_Lon_out.setText(self._translate("MainWindow", str(r2[0])))
        except:
            self.lineEdit_Lat_out.setText(self._translate("MainWindow", '')) 
            self.lineEdit_Lon_out.setText(self._translate("MainWindow", ''))   


    def click_covB2(self):
        v1 = self.lineEdit_Lat_in.text()
        v2 = self.lineEdit_Lon_in.text()
        try:
            r1, r2 = flood_tool.get_easting_northing_from_gps_lat_long(float(v1),float(v2))
            self.lineEdit_E_out.setText(self._translate("MainWindow", str(r1[0]))) 
            self.lineEdit_N_out.setText(self._translate("MainWindow", str(r2[0]))) 
        except:
            self.lineEdit_E_out.setText(self._translate("MainWindow", '')) 
            self.lineEdit_N_out.setText(self._translate("MainWindow", ''))
               
    
    def click_covB3(self):
        self.model.clear()
        filename = self.lineEdit_csv.text()
        data = pd.DataFrame()

        try:
            data = pd.read_csv('coordinate_file/' + filename + '.csv')
        except:
            return

        try:
            lats = data['Latitude'].values.tolist()
            lons = data['Longitude'].values.tolist()
            es, ns = flood_tool.get_easting_northing_from_gps_lat_long(lats, lons)
            data['Easting'] = es
            data['Northing'] = ns

            self.df = data
            self.loadDf()
        except:
            try:
                es = data['Easting'].values.tolist()
                ns = data['Northing'].values.tolist()
                lats, lons = flood_tool.get_gps_lat_long_from_easting_northing(es, ns)
                data['Latitude'] = lats
                data['Longitude'] = lons

                self.df = data
                self.loadDf()
            except: 
                return

    def loadDf(self):
        self.model.setHorizontalHeaderLabels(list(self.df))
        df_list = self.df.astype(str).values.tolist()
        for row in df_list:
            items = [
                    QtGui.QStandardItem(field)
                    for field in row
                ]
            self.model.appendRow(items)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
